name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    outputs:
      docker_image_tag: ${{ steps.image.outputs.tag }}

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build --logger trx

    - name: Test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit tests
        path: "**/*.trx"
        reporter: dotnet-trx

    - name: Publish
      run: dotnet publish --configuration Release --no-build src/DqtApi/DqtApi.csproj

    - name: Docker image tag
      id: image
      run: |
        echo ::set-output name=tag::ghcr.io/$GITHUB_REPOSITORY:sha-$(echo $GITHUB_SHA | cut -c -7)

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker build & push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ steps.image.outputs.tag }}